#ifndef __EVENT_LIST_H__
#define __EVENT_LIST_H__

#include "SlikeNet/MessageIdentifiers.h"

enum EVENTS
{
	FIRST = ID_USER_PACKET_ENUM + 1,	//USED for iteration DO NOT REMOVE

	SEND_CLIENT,				//Used by Server
	SEND_BROADCAST,

	REQUEST_EID,				//Used by Both
	MY_EID,
	EID_JOINED,
	EID_QUIT,
	SYNC_PLAYERS,

	MOVE_NORTH,
	MOVE_EAST,
	MOVE_SOUTH,
	MOVE_WEST,

	MOUSE_PRESSED,
	MOUSE_RELEASED,
	MOUSE_SCROLL,
	MOUSE_MOVE,

	UI_TOGGLE_FULLSCREEN,

	SEND_SERVER,				//Used by client
	ANIMATE,
	LOAD_ANIMATION_INFO,

	LOAD_MAP,

	LAST		//USED for iteration DO NOT REMOVE
};

#endif // __EVENT_LIST_H__