#ifndef __EVENT_LIST_H__
#define __EVENT_LIST_H__

#include "SlikeNet/MessageIdentifiers.h"

enum EVENTS
{
	FIRST = ID_USER_PACKET_ENUM + 1,	//USED for iteration DO NOT REMOVE

	SEND_CLIENT,				//Used by Server
	SEND_BROADCAST,

	REQUEST_EID,				//Used by Both
	MY_EID,
	EID_JOINED,
	EID_QUIT,
	SYNC_PLAYERS,

	MOVE_NORTH,
	MOVE_EAST,
	MOVE_SOUTH,
	MOVE_WEST,

	MOUSE_PRESSED,
	MOUSE_RELEASED,
	MOUSE_SCROLL,
	MOUSE_MOVE,

	SWITCH_FACING,

	UI_TOGGLE_FULLSCREEN,		//Used by client
	UI_TOGGLE_DEBUG,
	UI_LBL_NETWORK,

	SEND_SERVER,				
	ANIMATE,
	ANIMATION_LOAD_INFO,
	ANIMATION_REMOVE_INFO,
	ANIMATION_SWITCH_FACING,

	MAP_CREATE,
	MAP_LOAD,
	MAP_CHILD_ADD,
	MAP_CHILD_REMOVE,
	MAP_CAN_MOVE,
	MAP_TOGGLE_DEBUG,

	MOVES_V_CREATE,
	MOVES_V_REMOVE,

	CAMERA_LAYER_ADD,
	CAMERA_ZOOM_IN,
	CAMERA_ZOOM_OUT,

	AUDIO_C_CREATE,
	AUDIO_C_REMOVE,
	AUDIO_MUSIC_TOGGLE,

	LAST		//USED for iteration DO NOT REMOVE
};

#endif // __EVENT_LIST_H__