// ---------------------------------------
// Sprite definitions for Interface
// Generated with TexturePacker 4.11.1
//
// https://www.codeandweb.com/texturepacker
// 
// $TexturePacker:SmartUpdate:a26df97153f1ea0fde46d0b4196e313c:ff3d2a2548dabfd425907686d5baaad2:b8cc3ed6c9e421be43b9d989ba90b5a9$
// ---------------------------------------

#ifndef __INTERFACE_H__
#define __INTERFACE_H__

#include "cocos2d.h"

namespace TP
{

class Interface
{
public:
    /**
     * Add sprite frames contained in theInterface sheet to
     * the SpriteFrameCache.
     */
    static void addSpriteFramesToCache();

    /**
     * Remove sprite frames contained in theInterface sheet from
     * the SpriteFrameCache.
     */
    static void removeSpriteFramesFromCache();

    // ---------------------
    // sprite name constants
    // ---------------------
    static const std::string amigosClick;
    static const std::string amigosMenue;
    static const std::string amigosNuevoMensaje;
    static const std::string amigosRollover;
    static const std::string bOtonGrupoClick;
    static const std::string botonAceptarCambioContrasenia;
    static const std::string botonAceptarCambioContraseniaClick;
    static const std::string botonAceptarCambioContraseniaDisabled;
    static const std::string botonAceptarCambioContraseniaRollover;
    static const std::string botonAceptarSkills;
    static const std::string botonAceptarSkillsClick;
    static const std::string botonAceptarSkillsDisabled;
    static const std::string botonAceptarSkillsRollover;
    static const std::string botonAmigos;
    static const std::string botonAmigosAceptar;
    static const std::string botonAmigosAceptarClick;
    static const std::string botonAmigosAceptarRollover;
    static const std::string botonAmigosAceptarSolicitud;
    static const std::string botonAmigosAceptarSolicitudClick;
    static const std::string botonAmigosAceptarSolicitudRollover;
    static const std::string botonAmigosAgregar;
    static const std::string botonAmigosAgregarClick;
    static const std::string botonAmigosAgregarRollover;
    static const std::string botonAmigosClick;
    static const std::string botonAmigosNombre;
    static const std::string botonAmigosNombreClick;
    static const std::string botonAmigosNombreRollover;
    static const std::string botonAmigosRechazarSolicitud;
    static const std::string botonAmigosRechazarSolicitudClick;
    static const std::string botonAmigosRechazarSolicitudRollover;
    static const std::string botonAmigosRollover;
    static const std::string botonAmigosSalas;
    static const std::string botonAmigosSalasClick;
    static const std::string botonAmigosSalasRollover;
    static const std::string botonAmigosSolicitudes;
    static const std::string botonAmigosSolicitudesClick;
    static const std::string botonAmigosSolicitudesRollover;
    static const std::string botonAmigosTac;
    static const std::string botonAmigosTic;
    static const std::string botonArmaduras;
    static const std::string botonArmadurasClick;
    static const std::string botonArmadurasDisabled;
    static const std::string botonArmadurasHover;
    static const std::string botonArmas;
    static const std::string botonArmasClick;
    static const std::string botonArmasDisabled;
    static const std::string botonArmasHover;
    static const std::string botonBorrarPersonaje;
    static const std::string botonBorrarPersonajeClick;
    static const std::string botonBorrarPersonajeDisabled;
    static const std::string botonBorrarPersonajeRollover;
    static const std::string botonBovedaCuentaCambiar;
    static const std::string botonBovedaCuentaCambiarClick;
    static const std::string botonBovedaCuentaCambiarRollover;
    static const std::string botonBovedaCuentaCambiar_Click;
    static const std::string botonBovedaCuentaCambiar_Hover;
    static const std::string botonBovedaCuentaIngresar;
    static const std::string botonBovedaCuentaIngresarClick;
    static const std::string botonBovedaCuentaIngresarRollover;
    static const std::string botonBovedaCuentaIngresar_Click;
    static const std::string botonBovedaCuentaIngresar_Hover;
    static const std::string botonCambiarContrasenia;
    static const std::string botonCambiarContraseniaClick;
    static const std::string botonCambiarContraseniaDisabled;
    static const std::string botonCambiarContraseniaRollover;
    static const std::string botonCancelarBloqueado;
    static const std::string botonCerrarForm;
    static const std::string botonCerrarFormClick;
    static const std::string botonCerrarFormDisabled;
    static const std::string botonCerrarFormRollover;
    static const std::string botonCheck;
    static const std::string botonCheckbox;
    static const std::string botonClanActualizar;
    static const std::string botonClanActualizarClick;
    static const std::string botonClanActualizarDisabled;
    static const std::string botonClanActualizarRollover;
    static const std::string botonClanAlianza;
    static const std::string botonClanAlianzaClick;
    static const std::string botonClanAlianzaDisabled;
    static const std::string botonClanAlianzaRollover;
    static const std::string botonClanDetalles;
    static const std::string botonClanDetallesClick;
    static const std::string botonClanDetallesDisabled;
    static const std::string botonClanDetallesRollover;
    static const std::string botonClanEditarCodex;
    static const std::string botonClanEditarCodexAceptar;
    static const std::string botonClanEditarCodexAceptarClick;
    static const std::string botonClanEditarCodexAceptarDisabled;
    static const std::string botonClanEditarCodexAceptarRollover;
    static const std::string botonClanEditarCodexClick;
    static const std::string botonClanEditarCodexDisabled;
    static const std::string botonClanEditarCodexRollover;
    static const std::string botonClanEditarUrl;
    static const std::string botonClanEditarUrlClick;
    static const std::string botonClanEditarUrlDisabled;
    static const std::string botonClanEditarUrlRollover;
    static const std::string botonClanEditarWebsiteAceptar;
    static const std::string botonClanEditarWebsiteAceptarClick;
    static const std::string botonClanEditarWebsiteAceptarDisabled;
    static const std::string botonClanEditarWebsiteAceptarRollover;
    static const std::string botonClanElecciones;
    static const std::string botonClanEleccionesClick;
    static const std::string botonClanEleccionesDisabled;
    static const std::string botonClanEleccionesRollover;
    static const std::string botonClanInfoAlianza;
    static const std::string botonClanInfoAlianzaClick;
    static const std::string botonClanInfoAlianzaDisabled;
    static const std::string botonClanInfoAlianzaRollover;
    static const std::string botonClanInfoGuerra;
    static const std::string botonClanInfoGuerraClick;
    static const std::string botonClanInfoGuerraDisabled;
    static const std::string botonClanInfoGuerraRollover;
    static const std::string botonClanInfoPaz;
    static const std::string botonClanInfoPazClick;
    static const std::string botonClanInfoPazDisabled;
    static const std::string botonClanInfoPazRollover;
    static const std::string botonClanInfoSolicitarIngreso;
    static const std::string botonClanInfoSolicitarIngresoClick;
    static const std::string botonClanInfoSolicitarIngresoDisabled;
    static const std::string botonClanInfoSolicitarIngresoRollover;
    static const std::string botonClanMemberInfoAceptar;
    static const std::string botonClanMemberInfoAceptarClick;
    static const std::string botonClanMemberInfoAceptarDisabled;
    static const std::string botonClanMemberInfoAceptarRollover;
    static const std::string botonClanMemberInfoEchar;
    static const std::string botonClanMemberInfoEcharClick;
    static const std::string botonClanMemberInfoEcharDisabled;
    static const std::string botonClanMemberInfoEcharRollover;
    static const std::string botonClanMemberInfoPeticion;
    static const std::string botonClanMemberInfoPeticionClick;
    static const std::string botonClanMemberInfoPeticionDisabled;
    static const std::string botonClanMemberInfoPeticionRollover;
    static const std::string botonClanMemberInfoRechazar;
    static const std::string botonClanMemberInfoRechazarClick;
    static const std::string botonClanMemberInfoRechazarDisabled;
    static const std::string botonClanMemberInfoRechazarRollover;
    static const std::string botonClanOfertaAceptar;
    static const std::string botonClanOfertaAceptarClick;
    static const std::string botonClanOfertaAceptarDisabled;
    static const std::string botonClanOfertaAceptarRollover;
    static const std::string botonClanOfertaDetalles;
    static const std::string botonClanOfertaDetallesClick;
    static const std::string botonClanOfertaDetallesDisabled;
    static const std::string botonClanOfertaDetallesRollover;
    static const std::string botonClanOfertaRechazar;
    static const std::string botonClanOfertaRechazarClick;
    static const std::string botonClanOfertaRechazarDisabled;
    static const std::string botonClanOfertaRechazarRollover;
    static const std::string botonClanPaz;
    static const std::string botonClanPazClick;
    static const std::string botonClanPazDisabled;
    static const std::string botonClanPazRollover;
    static const std::string botonClanSolicitudCerrar;
    static const std::string botonClanSolicitudCerrarClick;
    static const std::string botonClanSolicitudCerrarDisabled;
    static const std::string botonClanSolicitudCerrarRollover;
    static const std::string botonClanSolicitudEnviar;
    static const std::string botonClanSolicitudEnviarClick;
    static const std::string botonClanSolicitudEnviarDisabled;
    static const std::string botonClanSolicitudEnviarRollover;
    static const std::string botonClanVerSolicitudAceptar;
    static const std::string botonClanVerSolicitudAceptarClick;
    static const std::string botonClanVerSolicitudAceptarDisabled;
    static const std::string botonClanVerSolicitudAceptarRollover;
    static const std::string botonClanes;
    static const std::string botonClanesClick;
    static const std::string botonClanesDisabled;
    static const std::string botonClanesRollover;
    static const std::string botonCodigoFuente;
    static const std::string botonCodigoFuenteClick;
    static const std::string botonCodigoFuenteRollover;
    static const std::string botonComercioComprar;
    static const std::string botonComercioComprarClick;
    static const std::string botonComercioComprarDisabled;
    static const std::string botonComercioComprarRollover;
    static const std::string botonComercioSalir;
    static const std::string botonComercioSalirClick;
    static const std::string botonComercioSalirDisabled;
    static const std::string botonComercioSalirRollover;
    static const std::string botonComercioVender;
    static const std::string botonComercioVenderClick;
    static const std::string botonComercioVenderDisabled;
    static const std::string botonComercioVenderRollover;
    static const std::string botonConectarse;
    static const std::string botonConectarseClick;
    static const std::string botonConectarseDisabled;
    static const std::string botonConectarseRollover;
    static const std::string botonConfig1;
    static const std::string botonConfig1Click;
    static const std::string botonConfig1Disabled;
    static const std::string botonConfig1Rollover;
    static const std::string botonConfig2;
    static const std::string botonConfig2Click;
    static const std::string botonConfig2Disabled;
    static const std::string botonConfig2Rollover;
    static const std::string botonConfig3;
    static const std::string botonConfig3Click;
    static const std::string botonConfig3Disabled;
    static const std::string botonConfig3Rollover;
    static const std::string botonConfig4;
    static const std::string botonConfig4Click;
    static const std::string botonConfig4Disabled;
    static const std::string botonConfig4Rollover;
    static const std::string botonConfig5;
    static const std::string botonConfig5Click;
    static const std::string botonConfig5Disabled;
    static const std::string botonConfig5Rollover;
    static const std::string botonConfig6;
    static const std::string botonConfig6Click;
    static const std::string botonConfig6Disabled;
    static const std::string botonConfig6Rollover;
    static const std::string botonConfig7;
    static const std::string botonConfig7Click;
    static const std::string botonConfig7Disabled;
    static const std::string botonConfig7Rollover;
    static const std::string botonConfig8;
    static const std::string botonConfig8Click;
    static const std::string botonConfig8Disabled;
    static const std::string botonConfig8Rollover;
    static const std::string botonConfig9;
    static const std::string botonConfig9Click;
    static const std::string botonConfig9Disabled;
    static const std::string botonConfig9Rollover;
    static const std::string botonConfigCargarDefault;
    static const std::string botonConfigCargarDefaultClick;
    static const std::string botonConfigCargarDefaultRollover;
    static const std::string botonConfigDefault;
    static const std::string botonConfigDefaultClick;
    static const std::string botonConfigDefaultDisabled;
    static const std::string botonConfigDefaultRollover;
    static const std::string botonConfigGuardar;
    static const std::string botonConfigGuardarClick;
    static const std::string botonConfigGuardarRollover;
    static const std::string botonConfigurarConsolaGuardar;
    static const std::string botonConfigurarConsolaGuardarClick;
    static const std::string botonConfigurarConsolaGuardarDisabled;
    static const std::string botonConfigurarConsolaGuardarRollover;
    static const std::string botonConfigurarConsolaSalir;
    static const std::string botonConfigurarConsolaSalirClick;
    static const std::string botonConfigurarConsolaSalirDisabled;
    static const std::string botonConfigurarConsolaSalirRollover;
    static const std::string botonConfirmarBloqueado;
    static const std::string botonConstruir;
    static const std::string botonConstruirClick;
    static const std::string botonConstruirDisabled;
    static const std::string botonConstruirHover;
    static const std::string botonCrafteoSalir;
    static const std::string botonCrafteoSalirClick;
    static const std::string botonCrafteoSalirDisabled;
    static const std::string botonCrafteoSalirRollover;
    static const std::string botonCrearCuenta;
    static const std::string botonCrearCuentaClick;
    static const std::string botonCrearCuentaDisabled;
    static const std::string botonCrearCuentaRollover;
    static const std::string botonCrearPersonaje;
    static const std::string botonCrearPersonajeClick;
    static const std::string botonCrearPersonajeDisabled;
    static const std::string botonCrearPersonajeRegresar;
    static const std::string botonCrearPersonajeRegresarClick;
    static const std::string botonCrearPersonajeRegresarDisabled;
    static const std::string botonCrearPersonajeRegresarRollover;
    static const std::string botonCrearPersonajeRollover;
    static const std::string botonCrearPersonajes;
    static const std::string botonCrearPersonajesClick;
    static const std::string botonCrearPersonajesDisabled;
    static const std::string botonCrearPersonajesRegresar;
    static const std::string botonCrearPersonajesRegresarClick;
    static const std::string botonCrearPersonajesRegresarDisabled;
    static const std::string botonCrearPersonajesRegresarRollover;
    static const std::string botonCrearPersonajesRollover;
    static const std::string botonCruzSalir;
    static const std::string botonCruzSalirClick;
    static const std::string botonCruzSalirDisabled;
    static const std::string botonCruzSalirRollover;
    static const std::string botonDeleteCharCancelar;
    static const std::string botonDeleteCharCancelarClick;
    static const std::string botonDeleteCharCancelarDisabled;
    static const std::string botonDeleteCharCancelarRollover;
    static const std::string botonDeleteCharConfirmar;
    static const std::string botonDeleteCharConfirmarClick;
    static const std::string botonDeleteCharConfirmarDisabled;
    static const std::string botonDeleteCharConfirmarRollover;
    static const std::string botonDialogosAplicar;
    static const std::string botonDialogosAplicarClick;
    static const std::string botonDialogosAplicarDisabled;
    static const std::string botonDialogosAplicarRollover;
    static const std::string botonDialogosDefecto;
    static const std::string botonDialogosDefectoClick;
    static const std::string botonDialogosDefectoDisabled;
    static const std::string botonDialogosDefectoRollover;
    static const std::string botonDialogosSalir;
    static const std::string botonDialogosSalirClick;
    static const std::string botonDialogosSalirDisabled;
    static const std::string botonDialogosSalirRollover;
    static const std::string botonDialogosTodoDefecto;
    static const std::string botonDialogosTodoDefectoClick;
    static const std::string botonDialogosTodoDefectoDisabled;
    static const std::string botonDialogosTodoDefectoRollover;
    static const std::string botonDuelo1v1;
    static const std::string botonDuelo1v1Click;
    static const std::string botonDuelo1v1Rollover;
    static const std::string botonDuelo2v2;
    static const std::string botonDuelo2v2Click;
    static const std::string botonDuelo2v2Rollover;
    static const std::string botonDuelo3v3;
    static const std::string botonDuelo3v3Click;
    static const std::string botonDuelo3v3Rollover;
    static const std::string botonDuelo4v4;
    static const std::string botonDuelo4v4Click;
    static const std::string botonDuelo4v4Rollover;
    static const std::string botonDueloAmigosTac;
    static const std::string botonDueloAmigosTic;
    static const std::string botonDueloCancelarEspera;
    static const std::string botonDueloCancelarEsperaClick;
    static const std::string botonDueloCancelarEsperaRollover;
    static const std::string botonEntrarPersonaje;
    static const std::string botonEntrarPersonajeClick;
    static const std::string botonEntrarPersonajeDisabled;
    static const std::string botonEntrarPersonajeRollover;
    static const std::string botonEnviarDuelo;
    static const std::string botonEnviarDueloClick;
    static const std::string botonEnviarDueloRollover;
    static const std::string botonEstadisticas;
    static const std::string botonEstadisticasClick;
    static const std::string botonEstadisticasDisabled;
    static const std::string botonEstadisticasRollover;
    static const std::string botonEstadisticasSalir;
    static const std::string botonEstadisticasSalirClick;
    static const std::string botonEstadisticasSalirDisabled;
    static const std::string botonEstadisticasSalirRollover;
    static const std::string botonFlechaDerecha;
    static const std::string botonFlechaDerechaRollover;
    static const std::string botonFlechaIzquierda;
    static const std::string botonFlechaIzquierdaRollover;
    static const std::string botonGrupo;
    static const std::string botonGrupoDisabled;
    static const std::string botonGrupoNuevoMensaje;
    static const std::string botonGrupoRollover;
    static const std::string botonItems;
    static const std::string botonItemsClick;
    static const std::string botonItemsDisabled;
    static const std::string botonItemsHover;
    static const std::string botonLiberarMascotas;
    static const std::string botonLiberarMascotasClick;
    static const std::string botonLiberarMascotasDisabled;
    static const std::string botonLiberarMascotasRollover;
    static const std::string botonListaClanesDetalle;
    static const std::string botonListaClanesDetalleClick;
    static const std::string botonListaClanesDetalleRollover;
    static const std::string botonManual;
    static const std::string botonManualClick;
    static const std::string botonManualRollover;
    static const std::string botonMapa;
    static const std::string botonMapaClick;
    static const std::string botonMapaDisabled;
    static const std::string botonMapaDungeons;
    static const std::string botonMapaDungeonsClick;
    static const std::string botonMapaDungeonsRollover;
    static const std::string botonMapaMundo;
    static const std::string botonMapaMundoClick;
    static const std::string botonMapaMundoRollover;
    static const std::string botonMapaRollover;
    static const std::string botonMasSkills;
    static const std::string botonMasSkillsClick;
    static const std::string botonMasSkillsDisabled;
    static const std::string botonMasSkillsRollover;
    static const std::string botonMascotaSalir;
    static const std::string botonMascotaSalirClick;
    static const std::string botonMascotaSalirDisabled;
    static const std::string botonMascotaSalirRollover;
    static const std::string botonMascotasLiberar;
    static const std::string botonMascotasLiberarClick;
    static const std::string botonMascotasLiberarDisabled;
    static const std::string botonMascotasLiberarRollover;
    static const std::string botonMascotasSeleccionar;
    static const std::string botonMascotasSeleccionarClick;
    static const std::string botonMascotasSeleccionarDisabled;
    static const std::string botonMascotasSeleccionarRollover;
    static const std::string botonMejorar;
    static const std::string botonMejorarClick;
    static const std::string botonMejorarDisabled;
    static const std::string botonMejorarHover;
    static const std::string botonMenosSkills;
    static const std::string botonMenosSkillsClick;
    static const std::string botonMenosSkillsDisabled;
    static const std::string botonMenosSkillsRollover;
    static const std::string botonMensajesGuardar;
    static const std::string botonMensajesGuardarClick;
    static const std::string botonMensajesGuardarDisabled;
    static const std::string botonMensajesGuardarRollover;
    static const std::string botonMensajesSalir;
    static const std::string botonMensajesSalirClick;
    static const std::string botonMensajesSalirDisabled;
    static const std::string botonMensajesSalirRollover;
    static const std::string botonMoverHechiAbajo;
    static const std::string botonMoverHechiAbajoClick;
    static const std::string botonMoverHechiAbajoRollover;
    static const std::string botonMoverHechiArriba;
    static const std::string botonMoverHechiArribaClick;
    static const std::string botonMoverHechiArribaRollover;
    static const std::string botonNoticiasClanAceptar;
    static const std::string botonNoticiasClanAceptarClick;
    static const std::string botonNoticiasClanAceptarDisabled;
    static const std::string botonNoticiasClanAceptarRollover;
    static const std::string botonOpciones;
    static const std::string botonOpcionesCambiarContrasenia;
    static const std::string botonOpcionesCambiarContraseniaClick;
    static const std::string botonOpcionesCambiarContraseniaDisabled;
    static const std::string botonOpcionesCambiarContraseniaRollover;
    static const std::string botonOpcionesClick;
    static const std::string botonOpcionesConfigurarTeclas;
    static const std::string botonOpcionesConfigurarTeclasClick;
    static const std::string botonOpcionesConfigurarTeclasDisabled;
    static const std::string botonOpcionesConfigurarTeclasRollover;
    static const std::string botonOpcionesDisabled;
    static const std::string botonOpcionesManual;
    static const std::string botonOpcionesManualClick;
    static const std::string botonOpcionesManualDisabled;
    static const std::string botonOpcionesManualRollover;
    static const std::string botonOpcionesMapa;
    static const std::string botonOpcionesMapaClick;
    static const std::string botonOpcionesMapaDisabled;
    static const std::string botonOpcionesMapaRollover;
    static const std::string botonOpcionesMensajesPersonalizados;
    static const std::string botonOpcionesMensajesPersonalizadosClick;
    static const std::string botonOpcionesMensajesPersonalizadosDisabled;
    static const std::string botonOpcionesMensajesPersonalizadosRollover;
    static const std::string botonOpcionesRadio;
    static const std::string botonOpcionesRadioClick;
    static const std::string botonOpcionesRadioDisabled;
    static const std::string botonOpcionesRadioRollover;
    static const std::string botonOpcionesRollover;
    static const std::string botonOpcionesSalir;
    static const std::string botonOpcionesSalirClick;
    static const std::string botonOpcionesSalirDisabled;
    static const std::string botonOpcionesSalirRollover;
    static const std::string botonOpcionesSoporte;
    static const std::string botonOpcionesSoporteClick;
    static const std::string botonOpcionesSoporteDisabled;
    static const std::string botonOpcionesSoporteRollover;
    static const std::string botonOpcionesTutorial;
    static const std::string botonOpcionesTutorialClick;
    static const std::string botonOpcionesTutorialDisabled;
    static const std::string botonOpcionesTutorialRollover;
    static const std::string botonRecuperarCuenta;
    static const std::string botonRecuperarCuentaClick;
    static const std::string botonRecuperarCuentaDisabled;
    static const std::string botonRecuperarCuentaRollover;
    static const std::string botonReglamento;
    static const std::string botonReglamentoClick;
    static const std::string botonReglamentoRollover;
    static const std::string botonResolucionNo;
    static const std::string botonResolucionNoClick;
    static const std::string botonResolucionNoDisabled;
    static const std::string botonResolucionNoRollover;
    static const std::string botonResolucionSi;
    static const std::string botonResolucionSiClick;
    static const std::string botonResolucionSiDisabled;
    static const std::string botonResolucionSiRollover;
    static const std::string botonSalir;
    static const std::string botonSalirClick;
    static const std::string botonSalirClickConnect;
    static const std::string botonSalirConnect;
    static const std::string botonSalirDisabled;
    static const std::string botonSalirMascotas;
    static const std::string botonSalirMascotasClick;
    static const std::string botonSalirMascotasDisabled;
    static const std::string botonSalirMascotasRollover;
    static const std::string botonSalirRollover;
    static const std::string botonSalirSkills;
    static const std::string botonSalirSkillsClick;
    static const std::string botonSalirSkillsDisabled;
    static const std::string botonSalirSkillsRollover;
    static const std::string botonSeleccionarMascotas;
    static const std::string botonSeleccionarMascotasClick;
    static const std::string botonSeleccionarMascotasDisabled;
    static const std::string botonSeleccionarMascotasRollover;
    static const std::string botonSkill;
    static const std::string botonSkillClick;
    static const std::string botonSkillDisabled;
    static const std::string botonSkillRollover;
    static const std::string botonSkillsAceptar;
    static const std::string botonSkillsAceptarClick;
    static const std::string botonSkillsAceptarDisabled;
    static const std::string botonSkillsAceptarRollover;
    static const std::string botonSkillsMas;
    static const std::string botonSkillsMasClick;
    static const std::string botonSkillsMasDisabled;
    static const std::string botonSkillsMasRollover;
    static const std::string botonSkillsMenos;
    static const std::string botonSkillsMenosClick;
    static const std::string botonSkillsMenosDisabled;
    static const std::string botonSkillsMenosRollover;
    static const std::string botonSkillsSalir;
    static const std::string botonSkillsSalirClick;
    static const std::string botonSkillsSalirDisabled;
    static const std::string botonSkillsSalirRollover;
    static const std::string botonTirar;
    static const std::string botonTirarClick;
    static const std::string botonTirarDisabled;
    static const std::string botonTirarRollover;
    static const std::string botonTirarTodo;
    static const std::string botonTirarTodoClick;
    static const std::string botonTirarTodoDisabled;
    static const std::string botonTirarTodoRollover;
    static const std::string botonTutorialAnterior;
    static const std::string botonTutorialAnteriorClick;
    static const std::string botonTutorialAnteriorDisabled;
    static const std::string botonTutorialAnteriorRollover;
    static const std::string botonTutorialSiguiente;
    static const std::string botonTutorialSiguienteClick;
    static const std::string botonTutorialSiguienteDisabled;
    static const std::string botonTutorialSiguienteRollover;
    static const std::string cajaMascota;
    static const std::string cajaMascotaClick;
    static const std::string cajaMascotaDisabled;
    static const std::string cajaMascotaRollover;
    static const std::string centroHechizos;
    static const std::string centroInventario;
    static const std::string estrellaBrillante;
    static const std::string estrellaMitad;
    static const std::string estrellaSimple;
    static const std::string iconConfigDisabled;
    static const std::string iconConfigEnabled;
    static const std::string marcoAmigoOffline;
    static const std::string marcoAmigoOnline;
    static const std::string marcoAmigoSala;
    static const std::string marcoAmigoSalaNuevoMensaje;
    static const std::string marcoAmigoSalaSeleccionada;
    static const std::string marcoItemsCrafteo;
    static const std::string minusDisabled;
    static const std::string minusEnabled;
    static const std::string noMostrarTutorial;
    static const std::string originArghal;
    static const std::string originBanderbill;
    static const std::string originLindos;
    static const std::string originNix;
    static const std::string originUllathorpe;
    static const std::string partyClick;
    static const std::string partyMenue;
    static const std::string partyRollover;
    static const std::string pestaniaAccionesApagado;
    static const std::string pestaniaAccionesMensajesNuevos;
    static const std::string pestaniaAccionesRollover;
    static const std::string pestaniaAccionesSeleccionado;
    static const std::string pestaniaAgrupacionesApagado;
    static const std::string pestaniaAgrupacionesMensajesNuevos;
    static const std::string pestaniaAgrupacionesRollover;
    static const std::string pestaniaAgrupacionesSeleccionado;
    static const std::string pestaniaAmigosApagado;
    static const std::string pestaniaAmigosMensajesNuevos;
    static const std::string pestaniaAmigosRollover;
    static const std::string pestaniaAmigosSeleccionado;
    static const std::string pestaniaGeneralApagado;
    static const std::string pestaniaGeneralMensajesNuevos;
    static const std::string pestaniaGeneralRollover;
    static const std::string pestaniaGeneralSeleccionado;
    static const std::string pestaniaPersonalizadaApagado;
    static const std::string pestaniaPersonalizadaMensajesNuevos;
    static const std::string pestaniaPersonalizadaRollover;
    static const std::string pestaniaPersonalizadaSeleccionado;
    static const std::string plusDisabled;
    static const std::string plusEnabled;
    static const std::string presentacion1;
    static const std::string presentacion2;
    static const std::string presentacion3;
    static const std::string presentacion4;
    static const std::string presentacion5;
    static const std::string presentacion6;
    static const std::string presentacion7;
    static const std::string presentacion8;
    static const std::string presentacion9;
    static const std::string progressBar;
    static const std::string recuadroVentanaMascotas;
    static const std::string recuadroVentanaMascotasClick;
    static const std::string recuadroVentanaMascotasDisabled;
    static const std::string recuadroVentanaMascotasRollover;
    static const std::string regresarRollover;
    static const std::string ventanaAmigos;
    static const std::string ventanaAmigosAgregar;
    static const std::string ventanaAmigosCambiarPerfil;
    static const std::string ventanaAmigosSolicitudes;
    static const std::string ventanaBorrarChar;
    static const std::string ventanaBovedaCuentaCambiarContrasenia;
    static const std::string ventanaBovedaCuentaPass;
    static const std::string ventanaCambiarContrasenia;
    static const std::string ventanaCantidad;
    static const std::string ventanaCargando;
    static const std::string ventanaClanAdmin;
    static const std::string ventanaClanInfo;
    static const std::string ventanaClanMemberInfo;
    static const std::string ventanaClanOfertaAlianza;
    static const std::string ventanaClanOfertaPaz;
    static const std::string ventanaClanSolicitud;
    static const std::string ventanaClanVerSolicitud;
    static const std::string ventanaComercio;
    static const std::string ventanaConectar;
    static const std::string ventanaConfigurarConsola;
    static const std::string ventanaConfigurarTeclas;
    static const std::string ventanaCrafteo;
    static const std::string ventanaCrearCuenta;
    static const std::string ventanaCrearPersonaje;
    static const std::string ventanaCuenta;
    static const std::string ventanaDialogos;
    static const std::string ventanaDuelo1v1;
    static const std::string ventanaDuelo2v2;
    static const std::string ventanaDuelo3v3;
    static const std::string ventanaDuelo4v4;
    static const std::string ventanaDuelos;
    static const std::string ventanaEditarCodex;
    static const std::string ventanaEditarWebsite;
    static const std::string ventanaEsperandoDuelo;
    static const std::string ventanaEstadisticaold_s;
    static const std::string ventanaEstadisticas;
    static const std::string ventanaListaClanes;
    static const std::string ventanaMapa;
    static const std::string ventanaMascotas;
    static const std::string ventanaMensajesPersonalizados;
    static const std::string ventanaNoticiasClan;
    static const std::string ventanaOpciones;
    static const std::string ventanaPrincipal;
    static const std::string ventanaResolucion;
    static const std::string ventanaSkills;
    static const std::string ventanaTutorial;

    // --------------
    // Sprite objects
    // --------------
    static cocos2d::Sprite *createAmigosClickSprite();
    static cocos2d::Sprite *createAmigosMenueSprite();
    static cocos2d::Sprite *createAmigosNuevoMensajeSprite();
    static cocos2d::Sprite *createAmigosRolloverSprite();
    static cocos2d::Sprite *createBOtonGrupoClickSprite();
    static cocos2d::Sprite *createBotonAceptarCambioContraseniaSprite();
    static cocos2d::Sprite *createBotonAceptarCambioContraseniaClickSprite();
    static cocos2d::Sprite *createBotonAceptarCambioContraseniaDisabledSprite();
    static cocos2d::Sprite *createBotonAceptarCambioContraseniaRolloverSprite();
    static cocos2d::Sprite *createBotonAceptarSkillsSprite();
    static cocos2d::Sprite *createBotonAceptarSkillsClickSprite();
    static cocos2d::Sprite *createBotonAceptarSkillsDisabledSprite();
    static cocos2d::Sprite *createBotonAceptarSkillsRolloverSprite();
    static cocos2d::Sprite *createBotonAmigosSprite();
    static cocos2d::Sprite *createBotonAmigosAceptarSprite();
    static cocos2d::Sprite *createBotonAmigosAceptarClickSprite();
    static cocos2d::Sprite *createBotonAmigosAceptarRolloverSprite();
    static cocos2d::Sprite *createBotonAmigosAceptarSolicitudSprite();
    static cocos2d::Sprite *createBotonAmigosAceptarSolicitudClickSprite();
    static cocos2d::Sprite *createBotonAmigosAceptarSolicitudRolloverSprite();
    static cocos2d::Sprite *createBotonAmigosAgregarSprite();
    static cocos2d::Sprite *createBotonAmigosAgregarClickSprite();
    static cocos2d::Sprite *createBotonAmigosAgregarRolloverSprite();
    static cocos2d::Sprite *createBotonAmigosClickSprite();
    static cocos2d::Sprite *createBotonAmigosNombreSprite();
    static cocos2d::Sprite *createBotonAmigosNombreClickSprite();
    static cocos2d::Sprite *createBotonAmigosNombreRolloverSprite();
    static cocos2d::Sprite *createBotonAmigosRechazarSolicitudSprite();
    static cocos2d::Sprite *createBotonAmigosRechazarSolicitudClickSprite();
    static cocos2d::Sprite *createBotonAmigosRechazarSolicitudRolloverSprite();
    static cocos2d::Sprite *createBotonAmigosRolloverSprite();
    static cocos2d::Sprite *createBotonAmigosSalasSprite();
    static cocos2d::Sprite *createBotonAmigosSalasClickSprite();
    static cocos2d::Sprite *createBotonAmigosSalasRolloverSprite();
    static cocos2d::Sprite *createBotonAmigosSolicitudesSprite();
    static cocos2d::Sprite *createBotonAmigosSolicitudesClickSprite();
    static cocos2d::Sprite *createBotonAmigosSolicitudesRolloverSprite();
    static cocos2d::Sprite *createBotonAmigosTacSprite();
    static cocos2d::Sprite *createBotonAmigosTicSprite();
    static cocos2d::Sprite *createBotonArmadurasSprite();
    static cocos2d::Sprite *createBotonArmadurasClickSprite();
    static cocos2d::Sprite *createBotonArmadurasDisabledSprite();
    static cocos2d::Sprite *createBotonArmadurasHoverSprite();
    static cocos2d::Sprite *createBotonArmasSprite();
    static cocos2d::Sprite *createBotonArmasClickSprite();
    static cocos2d::Sprite *createBotonArmasDisabledSprite();
    static cocos2d::Sprite *createBotonArmasHoverSprite();
    static cocos2d::Sprite *createBotonBorrarPersonajeSprite();
    static cocos2d::Sprite *createBotonBorrarPersonajeClickSprite();
    static cocos2d::Sprite *createBotonBorrarPersonajeDisabledSprite();
    static cocos2d::Sprite *createBotonBorrarPersonajeRolloverSprite();
    static cocos2d::Sprite *createBotonBovedaCuentaCambiarSprite();
    static cocos2d::Sprite *createBotonBovedaCuentaCambiarClickSprite();
    static cocos2d::Sprite *createBotonBovedaCuentaCambiarRolloverSprite();
    static cocos2d::Sprite *createBotonBovedaCuentaCambiar_ClickSprite();
    static cocos2d::Sprite *createBotonBovedaCuentaCambiar_HoverSprite();
    static cocos2d::Sprite *createBotonBovedaCuentaIngresarSprite();
    static cocos2d::Sprite *createBotonBovedaCuentaIngresarClickSprite();
    static cocos2d::Sprite *createBotonBovedaCuentaIngresarRolloverSprite();
    static cocos2d::Sprite *createBotonBovedaCuentaIngresar_ClickSprite();
    static cocos2d::Sprite *createBotonBovedaCuentaIngresar_HoverSprite();
    static cocos2d::Sprite *createBotonCambiarContraseniaSprite();
    static cocos2d::Sprite *createBotonCambiarContraseniaClickSprite();
    static cocos2d::Sprite *createBotonCambiarContraseniaDisabledSprite();
    static cocos2d::Sprite *createBotonCambiarContraseniaRolloverSprite();
    static cocos2d::Sprite *createBotonCancelarBloqueadoSprite();
    static cocos2d::Sprite *createBotonCerrarFormSprite();
    static cocos2d::Sprite *createBotonCerrarFormClickSprite();
    static cocos2d::Sprite *createBotonCerrarFormDisabledSprite();
    static cocos2d::Sprite *createBotonCerrarFormRolloverSprite();
    static cocos2d::Sprite *createBotonCheckSprite();
    static cocos2d::Sprite *createBotonCheckboxSprite();
    static cocos2d::Sprite *createBotonClanActualizarSprite();
    static cocos2d::Sprite *createBotonClanActualizarClickSprite();
    static cocos2d::Sprite *createBotonClanActualizarDisabledSprite();
    static cocos2d::Sprite *createBotonClanActualizarRolloverSprite();
    static cocos2d::Sprite *createBotonClanAlianzaSprite();
    static cocos2d::Sprite *createBotonClanAlianzaClickSprite();
    static cocos2d::Sprite *createBotonClanAlianzaDisabledSprite();
    static cocos2d::Sprite *createBotonClanAlianzaRolloverSprite();
    static cocos2d::Sprite *createBotonClanDetallesSprite();
    static cocos2d::Sprite *createBotonClanDetallesClickSprite();
    static cocos2d::Sprite *createBotonClanDetallesDisabledSprite();
    static cocos2d::Sprite *createBotonClanDetallesRolloverSprite();
    static cocos2d::Sprite *createBotonClanEditarCodexSprite();
    static cocos2d::Sprite *createBotonClanEditarCodexAceptarSprite();
    static cocos2d::Sprite *createBotonClanEditarCodexAceptarClickSprite();
    static cocos2d::Sprite *createBotonClanEditarCodexAceptarDisabledSprite();
    static cocos2d::Sprite *createBotonClanEditarCodexAceptarRolloverSprite();
    static cocos2d::Sprite *createBotonClanEditarCodexClickSprite();
    static cocos2d::Sprite *createBotonClanEditarCodexDisabledSprite();
    static cocos2d::Sprite *createBotonClanEditarCodexRolloverSprite();
    static cocos2d::Sprite *createBotonClanEditarUrlSprite();
    static cocos2d::Sprite *createBotonClanEditarUrlClickSprite();
    static cocos2d::Sprite *createBotonClanEditarUrlDisabledSprite();
    static cocos2d::Sprite *createBotonClanEditarUrlRolloverSprite();
    static cocos2d::Sprite *createBotonClanEditarWebsiteAceptarSprite();
    static cocos2d::Sprite *createBotonClanEditarWebsiteAceptarClickSprite();
    static cocos2d::Sprite *createBotonClanEditarWebsiteAceptarDisabledSprite();
    static cocos2d::Sprite *createBotonClanEditarWebsiteAceptarRolloverSprite();
    static cocos2d::Sprite *createBotonClanEleccionesSprite();
    static cocos2d::Sprite *createBotonClanEleccionesClickSprite();
    static cocos2d::Sprite *createBotonClanEleccionesDisabledSprite();
    static cocos2d::Sprite *createBotonClanEleccionesRolloverSprite();
    static cocos2d::Sprite *createBotonClanInfoAlianzaSprite();
    static cocos2d::Sprite *createBotonClanInfoAlianzaClickSprite();
    static cocos2d::Sprite *createBotonClanInfoAlianzaDisabledSprite();
    static cocos2d::Sprite *createBotonClanInfoAlianzaRolloverSprite();
    static cocos2d::Sprite *createBotonClanInfoGuerraSprite();
    static cocos2d::Sprite *createBotonClanInfoGuerraClickSprite();
    static cocos2d::Sprite *createBotonClanInfoGuerraDisabledSprite();
    static cocos2d::Sprite *createBotonClanInfoGuerraRolloverSprite();
    static cocos2d::Sprite *createBotonClanInfoPazSprite();
    static cocos2d::Sprite *createBotonClanInfoPazClickSprite();
    static cocos2d::Sprite *createBotonClanInfoPazDisabledSprite();
    static cocos2d::Sprite *createBotonClanInfoPazRolloverSprite();
    static cocos2d::Sprite *createBotonClanInfoSolicitarIngresoSprite();
    static cocos2d::Sprite *createBotonClanInfoSolicitarIngresoClickSprite();
    static cocos2d::Sprite *createBotonClanInfoSolicitarIngresoDisabledSprite();
    static cocos2d::Sprite *createBotonClanInfoSolicitarIngresoRolloverSprite();
    static cocos2d::Sprite *createBotonClanMemberInfoAceptarSprite();
    static cocos2d::Sprite *createBotonClanMemberInfoAceptarClickSprite();
    static cocos2d::Sprite *createBotonClanMemberInfoAceptarDisabledSprite();
    static cocos2d::Sprite *createBotonClanMemberInfoAceptarRolloverSprite();
    static cocos2d::Sprite *createBotonClanMemberInfoEcharSprite();
    static cocos2d::Sprite *createBotonClanMemberInfoEcharClickSprite();
    static cocos2d::Sprite *createBotonClanMemberInfoEcharDisabledSprite();
    static cocos2d::Sprite *createBotonClanMemberInfoEcharRolloverSprite();
    static cocos2d::Sprite *createBotonClanMemberInfoPeticionSprite();
    static cocos2d::Sprite *createBotonClanMemberInfoPeticionClickSprite();
    static cocos2d::Sprite *createBotonClanMemberInfoPeticionDisabledSprite();
    static cocos2d::Sprite *createBotonClanMemberInfoPeticionRolloverSprite();
    static cocos2d::Sprite *createBotonClanMemberInfoRechazarSprite();
    static cocos2d::Sprite *createBotonClanMemberInfoRechazarClickSprite();
    static cocos2d::Sprite *createBotonClanMemberInfoRechazarDisabledSprite();
    static cocos2d::Sprite *createBotonClanMemberInfoRechazarRolloverSprite();
    static cocos2d::Sprite *createBotonClanOfertaAceptarSprite();
    static cocos2d::Sprite *createBotonClanOfertaAceptarClickSprite();
    static cocos2d::Sprite *createBotonClanOfertaAceptarDisabledSprite();
    static cocos2d::Sprite *createBotonClanOfertaAceptarRolloverSprite();
    static cocos2d::Sprite *createBotonClanOfertaDetallesSprite();
    static cocos2d::Sprite *createBotonClanOfertaDetallesClickSprite();
    static cocos2d::Sprite *createBotonClanOfertaDetallesDisabledSprite();
    static cocos2d::Sprite *createBotonClanOfertaDetallesRolloverSprite();
    static cocos2d::Sprite *createBotonClanOfertaRechazarSprite();
    static cocos2d::Sprite *createBotonClanOfertaRechazarClickSprite();
    static cocos2d::Sprite *createBotonClanOfertaRechazarDisabledSprite();
    static cocos2d::Sprite *createBotonClanOfertaRechazarRolloverSprite();
    static cocos2d::Sprite *createBotonClanPazSprite();
    static cocos2d::Sprite *createBotonClanPazClickSprite();
    static cocos2d::Sprite *createBotonClanPazDisabledSprite();
    static cocos2d::Sprite *createBotonClanPazRolloverSprite();
    static cocos2d::Sprite *createBotonClanSolicitudCerrarSprite();
    static cocos2d::Sprite *createBotonClanSolicitudCerrarClickSprite();
    static cocos2d::Sprite *createBotonClanSolicitudCerrarDisabledSprite();
    static cocos2d::Sprite *createBotonClanSolicitudCerrarRolloverSprite();
    static cocos2d::Sprite *createBotonClanSolicitudEnviarSprite();
    static cocos2d::Sprite *createBotonClanSolicitudEnviarClickSprite();
    static cocos2d::Sprite *createBotonClanSolicitudEnviarDisabledSprite();
    static cocos2d::Sprite *createBotonClanSolicitudEnviarRolloverSprite();
    static cocos2d::Sprite *createBotonClanVerSolicitudAceptarSprite();
    static cocos2d::Sprite *createBotonClanVerSolicitudAceptarClickSprite();
    static cocos2d::Sprite *createBotonClanVerSolicitudAceptarDisabledSprite();
    static cocos2d::Sprite *createBotonClanVerSolicitudAceptarRolloverSprite();
    static cocos2d::Sprite *createBotonClanesSprite();
    static cocos2d::Sprite *createBotonClanesClickSprite();
    static cocos2d::Sprite *createBotonClanesDisabledSprite();
    static cocos2d::Sprite *createBotonClanesRolloverSprite();
    static cocos2d::Sprite *createBotonCodigoFuenteSprite();
    static cocos2d::Sprite *createBotonCodigoFuenteClickSprite();
    static cocos2d::Sprite *createBotonCodigoFuenteRolloverSprite();
    static cocos2d::Sprite *createBotonComercioComprarSprite();
    static cocos2d::Sprite *createBotonComercioComprarClickSprite();
    static cocos2d::Sprite *createBotonComercioComprarDisabledSprite();
    static cocos2d::Sprite *createBotonComercioComprarRolloverSprite();
    static cocos2d::Sprite *createBotonComercioSalirSprite();
    static cocos2d::Sprite *createBotonComercioSalirClickSprite();
    static cocos2d::Sprite *createBotonComercioSalirDisabledSprite();
    static cocos2d::Sprite *createBotonComercioSalirRolloverSprite();
    static cocos2d::Sprite *createBotonComercioVenderSprite();
    static cocos2d::Sprite *createBotonComercioVenderClickSprite();
    static cocos2d::Sprite *createBotonComercioVenderDisabledSprite();
    static cocos2d::Sprite *createBotonComercioVenderRolloverSprite();
    static cocos2d::Sprite *createBotonConectarseSprite();
    static cocos2d::Sprite *createBotonConectarseClickSprite();
    static cocos2d::Sprite *createBotonConectarseDisabledSprite();
    static cocos2d::Sprite *createBotonConectarseRolloverSprite();
    static cocos2d::Sprite *createBotonConfig1Sprite();
    static cocos2d::Sprite *createBotonConfig1ClickSprite();
    static cocos2d::Sprite *createBotonConfig1DisabledSprite();
    static cocos2d::Sprite *createBotonConfig1RolloverSprite();
    static cocos2d::Sprite *createBotonConfig2Sprite();
    static cocos2d::Sprite *createBotonConfig2ClickSprite();
    static cocos2d::Sprite *createBotonConfig2DisabledSprite();
    static cocos2d::Sprite *createBotonConfig2RolloverSprite();
    static cocos2d::Sprite *createBotonConfig3Sprite();
    static cocos2d::Sprite *createBotonConfig3ClickSprite();
    static cocos2d::Sprite *createBotonConfig3DisabledSprite();
    static cocos2d::Sprite *createBotonConfig3RolloverSprite();
    static cocos2d::Sprite *createBotonConfig4Sprite();
    static cocos2d::Sprite *createBotonConfig4ClickSprite();
    static cocos2d::Sprite *createBotonConfig4DisabledSprite();
    static cocos2d::Sprite *createBotonConfig4RolloverSprite();
    static cocos2d::Sprite *createBotonConfig5Sprite();
    static cocos2d::Sprite *createBotonConfig5ClickSprite();
    static cocos2d::Sprite *createBotonConfig5DisabledSprite();
    static cocos2d::Sprite *createBotonConfig5RolloverSprite();
    static cocos2d::Sprite *createBotonConfig6Sprite();
    static cocos2d::Sprite *createBotonConfig6ClickSprite();
    static cocos2d::Sprite *createBotonConfig6DisabledSprite();
    static cocos2d::Sprite *createBotonConfig6RolloverSprite();
    static cocos2d::Sprite *createBotonConfig7Sprite();
    static cocos2d::Sprite *createBotonConfig7ClickSprite();
    static cocos2d::Sprite *createBotonConfig7DisabledSprite();
    static cocos2d::Sprite *createBotonConfig7RolloverSprite();
    static cocos2d::Sprite *createBotonConfig8Sprite();
    static cocos2d::Sprite *createBotonConfig8ClickSprite();
    static cocos2d::Sprite *createBotonConfig8DisabledSprite();
    static cocos2d::Sprite *createBotonConfig8RolloverSprite();
    static cocos2d::Sprite *createBotonConfig9Sprite();
    static cocos2d::Sprite *createBotonConfig9ClickSprite();
    static cocos2d::Sprite *createBotonConfig9DisabledSprite();
    static cocos2d::Sprite *createBotonConfig9RolloverSprite();
    static cocos2d::Sprite *createBotonConfigCargarDefaultSprite();
    static cocos2d::Sprite *createBotonConfigCargarDefaultClickSprite();
    static cocos2d::Sprite *createBotonConfigCargarDefaultRolloverSprite();
    static cocos2d::Sprite *createBotonConfigDefaultSprite();
    static cocos2d::Sprite *createBotonConfigDefaultClickSprite();
    static cocos2d::Sprite *createBotonConfigDefaultDisabledSprite();
    static cocos2d::Sprite *createBotonConfigDefaultRolloverSprite();
    static cocos2d::Sprite *createBotonConfigGuardarSprite();
    static cocos2d::Sprite *createBotonConfigGuardarClickSprite();
    static cocos2d::Sprite *createBotonConfigGuardarRolloverSprite();
    static cocos2d::Sprite *createBotonConfigurarConsolaGuardarSprite();
    static cocos2d::Sprite *createBotonConfigurarConsolaGuardarClickSprite();
    static cocos2d::Sprite *createBotonConfigurarConsolaGuardarDisabledSprite();
    static cocos2d::Sprite *createBotonConfigurarConsolaGuardarRolloverSprite();
    static cocos2d::Sprite *createBotonConfigurarConsolaSalirSprite();
    static cocos2d::Sprite *createBotonConfigurarConsolaSalirClickSprite();
    static cocos2d::Sprite *createBotonConfigurarConsolaSalirDisabledSprite();
    static cocos2d::Sprite *createBotonConfigurarConsolaSalirRolloverSprite();
    static cocos2d::Sprite *createBotonConfirmarBloqueadoSprite();
    static cocos2d::Sprite *createBotonConstruirSprite();
    static cocos2d::Sprite *createBotonConstruirClickSprite();
    static cocos2d::Sprite *createBotonConstruirDisabledSprite();
    static cocos2d::Sprite *createBotonConstruirHoverSprite();
    static cocos2d::Sprite *createBotonCrafteoSalirSprite();
    static cocos2d::Sprite *createBotonCrafteoSalirClickSprite();
    static cocos2d::Sprite *createBotonCrafteoSalirDisabledSprite();
    static cocos2d::Sprite *createBotonCrafteoSalirRolloverSprite();
    static cocos2d::Sprite *createBotonCrearCuentaSprite();
    static cocos2d::Sprite *createBotonCrearCuentaClickSprite();
    static cocos2d::Sprite *createBotonCrearCuentaDisabledSprite();
    static cocos2d::Sprite *createBotonCrearCuentaRolloverSprite();
    static cocos2d::Sprite *createBotonCrearPersonajeSprite();
    static cocos2d::Sprite *createBotonCrearPersonajeClickSprite();
    static cocos2d::Sprite *createBotonCrearPersonajeDisabledSprite();
    static cocos2d::Sprite *createBotonCrearPersonajeRegresarSprite();
    static cocos2d::Sprite *createBotonCrearPersonajeRegresarClickSprite();
    static cocos2d::Sprite *createBotonCrearPersonajeRegresarDisabledSprite();
    static cocos2d::Sprite *createBotonCrearPersonajeRegresarRolloverSprite();
    static cocos2d::Sprite *createBotonCrearPersonajeRolloverSprite();
    static cocos2d::Sprite *createBotonCrearPersonajesSprite();
    static cocos2d::Sprite *createBotonCrearPersonajesClickSprite();
    static cocos2d::Sprite *createBotonCrearPersonajesDisabledSprite();
    static cocos2d::Sprite *createBotonCrearPersonajesRegresarSprite();
    static cocos2d::Sprite *createBotonCrearPersonajesRegresarClickSprite();
    static cocos2d::Sprite *createBotonCrearPersonajesRegresarDisabledSprite();
    static cocos2d::Sprite *createBotonCrearPersonajesRegresarRolloverSprite();
    static cocos2d::Sprite *createBotonCrearPersonajesRolloverSprite();
    static cocos2d::Sprite *createBotonCruzSalirSprite();
    static cocos2d::Sprite *createBotonCruzSalirClickSprite();
    static cocos2d::Sprite *createBotonCruzSalirDisabledSprite();
    static cocos2d::Sprite *createBotonCruzSalirRolloverSprite();
    static cocos2d::Sprite *createBotonDeleteCharCancelarSprite();
    static cocos2d::Sprite *createBotonDeleteCharCancelarClickSprite();
    static cocos2d::Sprite *createBotonDeleteCharCancelarDisabledSprite();
    static cocos2d::Sprite *createBotonDeleteCharCancelarRolloverSprite();
    static cocos2d::Sprite *createBotonDeleteCharConfirmarSprite();
    static cocos2d::Sprite *createBotonDeleteCharConfirmarClickSprite();
    static cocos2d::Sprite *createBotonDeleteCharConfirmarDisabledSprite();
    static cocos2d::Sprite *createBotonDeleteCharConfirmarRolloverSprite();
    static cocos2d::Sprite *createBotonDialogosAplicarSprite();
    static cocos2d::Sprite *createBotonDialogosAplicarClickSprite();
    static cocos2d::Sprite *createBotonDialogosAplicarDisabledSprite();
    static cocos2d::Sprite *createBotonDialogosAplicarRolloverSprite();
    static cocos2d::Sprite *createBotonDialogosDefectoSprite();
    static cocos2d::Sprite *createBotonDialogosDefectoClickSprite();
    static cocos2d::Sprite *createBotonDialogosDefectoDisabledSprite();
    static cocos2d::Sprite *createBotonDialogosDefectoRolloverSprite();
    static cocos2d::Sprite *createBotonDialogosSalirSprite();
    static cocos2d::Sprite *createBotonDialogosSalirClickSprite();
    static cocos2d::Sprite *createBotonDialogosSalirDisabledSprite();
    static cocos2d::Sprite *createBotonDialogosSalirRolloverSprite();
    static cocos2d::Sprite *createBotonDialogosTodoDefectoSprite();
    static cocos2d::Sprite *createBotonDialogosTodoDefectoClickSprite();
    static cocos2d::Sprite *createBotonDialogosTodoDefectoDisabledSprite();
    static cocos2d::Sprite *createBotonDialogosTodoDefectoRolloverSprite();
    static cocos2d::Sprite *createBotonDuelo1v1Sprite();
    static cocos2d::Sprite *createBotonDuelo1v1ClickSprite();
    static cocos2d::Sprite *createBotonDuelo1v1RolloverSprite();
    static cocos2d::Sprite *createBotonDuelo2v2Sprite();
    static cocos2d::Sprite *createBotonDuelo2v2ClickSprite();
    static cocos2d::Sprite *createBotonDuelo2v2RolloverSprite();
    static cocos2d::Sprite *createBotonDuelo3v3Sprite();
    static cocos2d::Sprite *createBotonDuelo3v3ClickSprite();
    static cocos2d::Sprite *createBotonDuelo3v3RolloverSprite();
    static cocos2d::Sprite *createBotonDuelo4v4Sprite();
    static cocos2d::Sprite *createBotonDuelo4v4ClickSprite();
    static cocos2d::Sprite *createBotonDuelo4v4RolloverSprite();
    static cocos2d::Sprite *createBotonDueloAmigosTacSprite();
    static cocos2d::Sprite *createBotonDueloAmigosTicSprite();
    static cocos2d::Sprite *createBotonDueloCancelarEsperaSprite();
    static cocos2d::Sprite *createBotonDueloCancelarEsperaClickSprite();
    static cocos2d::Sprite *createBotonDueloCancelarEsperaRolloverSprite();
    static cocos2d::Sprite *createBotonEntrarPersonajeSprite();
    static cocos2d::Sprite *createBotonEntrarPersonajeClickSprite();
    static cocos2d::Sprite *createBotonEntrarPersonajeDisabledSprite();
    static cocos2d::Sprite *createBotonEntrarPersonajeRolloverSprite();
    static cocos2d::Sprite *createBotonEnviarDueloSprite();
    static cocos2d::Sprite *createBotonEnviarDueloClickSprite();
    static cocos2d::Sprite *createBotonEnviarDueloRolloverSprite();
    static cocos2d::Sprite *createBotonEstadisticasSprite();
    static cocos2d::Sprite *createBotonEstadisticasClickSprite();
    static cocos2d::Sprite *createBotonEstadisticasDisabledSprite();
    static cocos2d::Sprite *createBotonEstadisticasRolloverSprite();
    static cocos2d::Sprite *createBotonEstadisticasSalirSprite();
    static cocos2d::Sprite *createBotonEstadisticasSalirClickSprite();
    static cocos2d::Sprite *createBotonEstadisticasSalirDisabledSprite();
    static cocos2d::Sprite *createBotonEstadisticasSalirRolloverSprite();
    static cocos2d::Sprite *createBotonFlechaDerechaSprite();
    static cocos2d::Sprite *createBotonFlechaDerechaRolloverSprite();
    static cocos2d::Sprite *createBotonFlechaIzquierdaSprite();
    static cocos2d::Sprite *createBotonFlechaIzquierdaRolloverSprite();
    static cocos2d::Sprite *createBotonGrupoSprite();
    static cocos2d::Sprite *createBotonGrupoDisabledSprite();
    static cocos2d::Sprite *createBotonGrupoNuevoMensajeSprite();
    static cocos2d::Sprite *createBotonGrupoRolloverSprite();
    static cocos2d::Sprite *createBotonItemsSprite();
    static cocos2d::Sprite *createBotonItemsClickSprite();
    static cocos2d::Sprite *createBotonItemsDisabledSprite();
    static cocos2d::Sprite *createBotonItemsHoverSprite();
    static cocos2d::Sprite *createBotonLiberarMascotasSprite();
    static cocos2d::Sprite *createBotonLiberarMascotasClickSprite();
    static cocos2d::Sprite *createBotonLiberarMascotasDisabledSprite();
    static cocos2d::Sprite *createBotonLiberarMascotasRolloverSprite();
    static cocos2d::Sprite *createBotonListaClanesDetalleSprite();
    static cocos2d::Sprite *createBotonListaClanesDetalleClickSprite();
    static cocos2d::Sprite *createBotonListaClanesDetalleRolloverSprite();
    static cocos2d::Sprite *createBotonManualSprite();
    static cocos2d::Sprite *createBotonManualClickSprite();
    static cocos2d::Sprite *createBotonManualRolloverSprite();
    static cocos2d::Sprite *createBotonMapaSprite();
    static cocos2d::Sprite *createBotonMapaClickSprite();
    static cocos2d::Sprite *createBotonMapaDisabledSprite();
    static cocos2d::Sprite *createBotonMapaDungeonsSprite();
    static cocos2d::Sprite *createBotonMapaDungeonsClickSprite();
    static cocos2d::Sprite *createBotonMapaDungeonsRolloverSprite();
    static cocos2d::Sprite *createBotonMapaMundoSprite();
    static cocos2d::Sprite *createBotonMapaMundoClickSprite();
    static cocos2d::Sprite *createBotonMapaMundoRolloverSprite();
    static cocos2d::Sprite *createBotonMapaRolloverSprite();
    static cocos2d::Sprite *createBotonMasSkillsSprite();
    static cocos2d::Sprite *createBotonMasSkillsClickSprite();
    static cocos2d::Sprite *createBotonMasSkillsDisabledSprite();
    static cocos2d::Sprite *createBotonMasSkillsRolloverSprite();
    static cocos2d::Sprite *createBotonMascotaSalirSprite();
    static cocos2d::Sprite *createBotonMascotaSalirClickSprite();
    static cocos2d::Sprite *createBotonMascotaSalirDisabledSprite();
    static cocos2d::Sprite *createBotonMascotaSalirRolloverSprite();
    static cocos2d::Sprite *createBotonMascotasLiberarSprite();
    static cocos2d::Sprite *createBotonMascotasLiberarClickSprite();
    static cocos2d::Sprite *createBotonMascotasLiberarDisabledSprite();
    static cocos2d::Sprite *createBotonMascotasLiberarRolloverSprite();
    static cocos2d::Sprite *createBotonMascotasSeleccionarSprite();
    static cocos2d::Sprite *createBotonMascotasSeleccionarClickSprite();
    static cocos2d::Sprite *createBotonMascotasSeleccionarDisabledSprite();
    static cocos2d::Sprite *createBotonMascotasSeleccionarRolloverSprite();
    static cocos2d::Sprite *createBotonMejorarSprite();
    static cocos2d::Sprite *createBotonMejorarClickSprite();
    static cocos2d::Sprite *createBotonMejorarDisabledSprite();
    static cocos2d::Sprite *createBotonMejorarHoverSprite();
    static cocos2d::Sprite *createBotonMenosSkillsSprite();
    static cocos2d::Sprite *createBotonMenosSkillsClickSprite();
    static cocos2d::Sprite *createBotonMenosSkillsDisabledSprite();
    static cocos2d::Sprite *createBotonMenosSkillsRolloverSprite();
    static cocos2d::Sprite *createBotonMensajesGuardarSprite();
    static cocos2d::Sprite *createBotonMensajesGuardarClickSprite();
    static cocos2d::Sprite *createBotonMensajesGuardarDisabledSprite();
    static cocos2d::Sprite *createBotonMensajesGuardarRolloverSprite();
    static cocos2d::Sprite *createBotonMensajesSalirSprite();
    static cocos2d::Sprite *createBotonMensajesSalirClickSprite();
    static cocos2d::Sprite *createBotonMensajesSalirDisabledSprite();
    static cocos2d::Sprite *createBotonMensajesSalirRolloverSprite();
    static cocos2d::Sprite *createBotonMoverHechiAbajoSprite();
    static cocos2d::Sprite *createBotonMoverHechiAbajoClickSprite();
    static cocos2d::Sprite *createBotonMoverHechiAbajoRolloverSprite();
    static cocos2d::Sprite *createBotonMoverHechiArribaSprite();
    static cocos2d::Sprite *createBotonMoverHechiArribaClickSprite();
    static cocos2d::Sprite *createBotonMoverHechiArribaRolloverSprite();
    static cocos2d::Sprite *createBotonNoticiasClanAceptarSprite();
    static cocos2d::Sprite *createBotonNoticiasClanAceptarClickSprite();
    static cocos2d::Sprite *createBotonNoticiasClanAceptarDisabledSprite();
    static cocos2d::Sprite *createBotonNoticiasClanAceptarRolloverSprite();
    static cocos2d::Sprite *createBotonOpcionesSprite();
    static cocos2d::Sprite *createBotonOpcionesCambiarContraseniaSprite();
    static cocos2d::Sprite *createBotonOpcionesCambiarContraseniaClickSprite();
    static cocos2d::Sprite *createBotonOpcionesCambiarContraseniaDisabledSprite();
    static cocos2d::Sprite *createBotonOpcionesCambiarContraseniaRolloverSprite();
    static cocos2d::Sprite *createBotonOpcionesClickSprite();
    static cocos2d::Sprite *createBotonOpcionesConfigurarTeclasSprite();
    static cocos2d::Sprite *createBotonOpcionesConfigurarTeclasClickSprite();
    static cocos2d::Sprite *createBotonOpcionesConfigurarTeclasDisabledSprite();
    static cocos2d::Sprite *createBotonOpcionesConfigurarTeclasRolloverSprite();
    static cocos2d::Sprite *createBotonOpcionesDisabledSprite();
    static cocos2d::Sprite *createBotonOpcionesManualSprite();
    static cocos2d::Sprite *createBotonOpcionesManualClickSprite();
    static cocos2d::Sprite *createBotonOpcionesManualDisabledSprite();
    static cocos2d::Sprite *createBotonOpcionesManualRolloverSprite();
    static cocos2d::Sprite *createBotonOpcionesMapaSprite();
    static cocos2d::Sprite *createBotonOpcionesMapaClickSprite();
    static cocos2d::Sprite *createBotonOpcionesMapaDisabledSprite();
    static cocos2d::Sprite *createBotonOpcionesMapaRolloverSprite();
    static cocos2d::Sprite *createBotonOpcionesMensajesPersonalizadosSprite();
    static cocos2d::Sprite *createBotonOpcionesMensajesPersonalizadosClickSprite();
    static cocos2d::Sprite *createBotonOpcionesMensajesPersonalizadosDisabledSprite();
    static cocos2d::Sprite *createBotonOpcionesMensajesPersonalizadosRolloverSprite();
    static cocos2d::Sprite *createBotonOpcionesRadioSprite();
    static cocos2d::Sprite *createBotonOpcionesRadioClickSprite();
    static cocos2d::Sprite *createBotonOpcionesRadioDisabledSprite();
    static cocos2d::Sprite *createBotonOpcionesRadioRolloverSprite();
    static cocos2d::Sprite *createBotonOpcionesRolloverSprite();
    static cocos2d::Sprite *createBotonOpcionesSalirSprite();
    static cocos2d::Sprite *createBotonOpcionesSalirClickSprite();
    static cocos2d::Sprite *createBotonOpcionesSalirDisabledSprite();
    static cocos2d::Sprite *createBotonOpcionesSalirRolloverSprite();
    static cocos2d::Sprite *createBotonOpcionesSoporteSprite();
    static cocos2d::Sprite *createBotonOpcionesSoporteClickSprite();
    static cocos2d::Sprite *createBotonOpcionesSoporteDisabledSprite();
    static cocos2d::Sprite *createBotonOpcionesSoporteRolloverSprite();
    static cocos2d::Sprite *createBotonOpcionesTutorialSprite();
    static cocos2d::Sprite *createBotonOpcionesTutorialClickSprite();
    static cocos2d::Sprite *createBotonOpcionesTutorialDisabledSprite();
    static cocos2d::Sprite *createBotonOpcionesTutorialRolloverSprite();
    static cocos2d::Sprite *createBotonRecuperarCuentaSprite();
    static cocos2d::Sprite *createBotonRecuperarCuentaClickSprite();
    static cocos2d::Sprite *createBotonRecuperarCuentaDisabledSprite();
    static cocos2d::Sprite *createBotonRecuperarCuentaRolloverSprite();
    static cocos2d::Sprite *createBotonReglamentoSprite();
    static cocos2d::Sprite *createBotonReglamentoClickSprite();
    static cocos2d::Sprite *createBotonReglamentoRolloverSprite();
    static cocos2d::Sprite *createBotonResolucionNoSprite();
    static cocos2d::Sprite *createBotonResolucionNoClickSprite();
    static cocos2d::Sprite *createBotonResolucionNoDisabledSprite();
    static cocos2d::Sprite *createBotonResolucionNoRolloverSprite();
    static cocos2d::Sprite *createBotonResolucionSiSprite();
    static cocos2d::Sprite *createBotonResolucionSiClickSprite();
    static cocos2d::Sprite *createBotonResolucionSiDisabledSprite();
    static cocos2d::Sprite *createBotonResolucionSiRolloverSprite();
    static cocos2d::Sprite *createBotonSalirSprite();
    static cocos2d::Sprite *createBotonSalirClickSprite();
    static cocos2d::Sprite *createBotonSalirClickConnectSprite();
    static cocos2d::Sprite *createBotonSalirConnectSprite();
    static cocos2d::Sprite *createBotonSalirDisabledSprite();
    static cocos2d::Sprite *createBotonSalirMascotasSprite();
    static cocos2d::Sprite *createBotonSalirMascotasClickSprite();
    static cocos2d::Sprite *createBotonSalirMascotasDisabledSprite();
    static cocos2d::Sprite *createBotonSalirMascotasRolloverSprite();
    static cocos2d::Sprite *createBotonSalirRolloverSprite();
    static cocos2d::Sprite *createBotonSalirSkillsSprite();
    static cocos2d::Sprite *createBotonSalirSkillsClickSprite();
    static cocos2d::Sprite *createBotonSalirSkillsDisabledSprite();
    static cocos2d::Sprite *createBotonSalirSkillsRolloverSprite();
    static cocos2d::Sprite *createBotonSeleccionarMascotasSprite();
    static cocos2d::Sprite *createBotonSeleccionarMascotasClickSprite();
    static cocos2d::Sprite *createBotonSeleccionarMascotasDisabledSprite();
    static cocos2d::Sprite *createBotonSeleccionarMascotasRolloverSprite();
    static cocos2d::Sprite *createBotonSkillSprite();
    static cocos2d::Sprite *createBotonSkillClickSprite();
    static cocos2d::Sprite *createBotonSkillDisabledSprite();
    static cocos2d::Sprite *createBotonSkillRolloverSprite();
    static cocos2d::Sprite *createBotonSkillsAceptarSprite();
    static cocos2d::Sprite *createBotonSkillsAceptarClickSprite();
    static cocos2d::Sprite *createBotonSkillsAceptarDisabledSprite();
    static cocos2d::Sprite *createBotonSkillsAceptarRolloverSprite();
    static cocos2d::Sprite *createBotonSkillsMasSprite();
    static cocos2d::Sprite *createBotonSkillsMasClickSprite();
    static cocos2d::Sprite *createBotonSkillsMasDisabledSprite();
    static cocos2d::Sprite *createBotonSkillsMasRolloverSprite();
    static cocos2d::Sprite *createBotonSkillsMenosSprite();
    static cocos2d::Sprite *createBotonSkillsMenosClickSprite();
    static cocos2d::Sprite *createBotonSkillsMenosDisabledSprite();
    static cocos2d::Sprite *createBotonSkillsMenosRolloverSprite();
    static cocos2d::Sprite *createBotonSkillsSalirSprite();
    static cocos2d::Sprite *createBotonSkillsSalirClickSprite();
    static cocos2d::Sprite *createBotonSkillsSalirDisabledSprite();
    static cocos2d::Sprite *createBotonSkillsSalirRolloverSprite();
    static cocos2d::Sprite *createBotonTirarSprite();
    static cocos2d::Sprite *createBotonTirarClickSprite();
    static cocos2d::Sprite *createBotonTirarDisabledSprite();
    static cocos2d::Sprite *createBotonTirarRolloverSprite();
    static cocos2d::Sprite *createBotonTirarTodoSprite();
    static cocos2d::Sprite *createBotonTirarTodoClickSprite();
    static cocos2d::Sprite *createBotonTirarTodoDisabledSprite();
    static cocos2d::Sprite *createBotonTirarTodoRolloverSprite();
    static cocos2d::Sprite *createBotonTutorialAnteriorSprite();
    static cocos2d::Sprite *createBotonTutorialAnteriorClickSprite();
    static cocos2d::Sprite *createBotonTutorialAnteriorDisabledSprite();
    static cocos2d::Sprite *createBotonTutorialAnteriorRolloverSprite();
    static cocos2d::Sprite *createBotonTutorialSiguienteSprite();
    static cocos2d::Sprite *createBotonTutorialSiguienteClickSprite();
    static cocos2d::Sprite *createBotonTutorialSiguienteDisabledSprite();
    static cocos2d::Sprite *createBotonTutorialSiguienteRolloverSprite();
    static cocos2d::Sprite *createCajaMascotaSprite();
    static cocos2d::Sprite *createCajaMascotaClickSprite();
    static cocos2d::Sprite *createCajaMascotaDisabledSprite();
    static cocos2d::Sprite *createCajaMascotaRolloverSprite();
    static cocos2d::Sprite *createCentroHechizosSprite();
    static cocos2d::Sprite *createCentroInventarioSprite();
    static cocos2d::Sprite *createEstrellaBrillanteSprite();
    static cocos2d::Sprite *createEstrellaMitadSprite();
    static cocos2d::Sprite *createEstrellaSimpleSprite();
    static cocos2d::Sprite *createIconConfigDisabledSprite();
    static cocos2d::Sprite *createIconConfigEnabledSprite();
    static cocos2d::Sprite *createMarcoAmigoOfflineSprite();
    static cocos2d::Sprite *createMarcoAmigoOnlineSprite();
    static cocos2d::Sprite *createMarcoAmigoSalaSprite();
    static cocos2d::Sprite *createMarcoAmigoSalaNuevoMensajeSprite();
    static cocos2d::Sprite *createMarcoAmigoSalaSeleccionadaSprite();
    static cocos2d::Sprite *createMarcoItemsCrafteoSprite();
    static cocos2d::Sprite *createMinusDisabledSprite();
    static cocos2d::Sprite *createMinusEnabledSprite();
    static cocos2d::Sprite *createNoMostrarTutorialSprite();
    static cocos2d::Sprite *createOriginArghalSprite();
    static cocos2d::Sprite *createOriginBanderbillSprite();
    static cocos2d::Sprite *createOriginLindosSprite();
    static cocos2d::Sprite *createOriginNixSprite();
    static cocos2d::Sprite *createOriginUllathorpeSprite();
    static cocos2d::Sprite *createPartyClickSprite();
    static cocos2d::Sprite *createPartyMenueSprite();
    static cocos2d::Sprite *createPartyRolloverSprite();
    static cocos2d::Sprite *createPestaniaAccionesApagadoSprite();
    static cocos2d::Sprite *createPestaniaAccionesMensajesNuevosSprite();
    static cocos2d::Sprite *createPestaniaAccionesRolloverSprite();
    static cocos2d::Sprite *createPestaniaAccionesSeleccionadoSprite();
    static cocos2d::Sprite *createPestaniaAgrupacionesApagadoSprite();
    static cocos2d::Sprite *createPestaniaAgrupacionesMensajesNuevosSprite();
    static cocos2d::Sprite *createPestaniaAgrupacionesRolloverSprite();
    static cocos2d::Sprite *createPestaniaAgrupacionesSeleccionadoSprite();
    static cocos2d::Sprite *createPestaniaAmigosApagadoSprite();
    static cocos2d::Sprite *createPestaniaAmigosMensajesNuevosSprite();
    static cocos2d::Sprite *createPestaniaAmigosRolloverSprite();
    static cocos2d::Sprite *createPestaniaAmigosSeleccionadoSprite();
    static cocos2d::Sprite *createPestaniaGeneralApagadoSprite();
    static cocos2d::Sprite *createPestaniaGeneralMensajesNuevosSprite();
    static cocos2d::Sprite *createPestaniaGeneralRolloverSprite();
    static cocos2d::Sprite *createPestaniaGeneralSeleccionadoSprite();
    static cocos2d::Sprite *createPestaniaPersonalizadaApagadoSprite();
    static cocos2d::Sprite *createPestaniaPersonalizadaMensajesNuevosSprite();
    static cocos2d::Sprite *createPestaniaPersonalizadaRolloverSprite();
    static cocos2d::Sprite *createPestaniaPersonalizadaSeleccionadoSprite();
    static cocos2d::Sprite *createPlusDisabledSprite();
    static cocos2d::Sprite *createPlusEnabledSprite();
    static cocos2d::Sprite *createPresentacion1Sprite();
    static cocos2d::Sprite *createPresentacion2Sprite();
    static cocos2d::Sprite *createPresentacion3Sprite();
    static cocos2d::Sprite *createPresentacion4Sprite();
    static cocos2d::Sprite *createPresentacion5Sprite();
    static cocos2d::Sprite *createPresentacion6Sprite();
    static cocos2d::Sprite *createPresentacion7Sprite();
    static cocos2d::Sprite *createPresentacion8Sprite();
    static cocos2d::Sprite *createPresentacion9Sprite();
    static cocos2d::Sprite *createProgressBarSprite();
    static cocos2d::Sprite *createRecuadroVentanaMascotasSprite();
    static cocos2d::Sprite *createRecuadroVentanaMascotasClickSprite();
    static cocos2d::Sprite *createRecuadroVentanaMascotasDisabledSprite();
    static cocos2d::Sprite *createRecuadroVentanaMascotasRolloverSprite();
    static cocos2d::Sprite *createRegresarRolloverSprite();
    static cocos2d::Sprite *createVentanaAmigosSprite();
    static cocos2d::Sprite *createVentanaAmigosAgregarSprite();
    static cocos2d::Sprite *createVentanaAmigosCambiarPerfilSprite();
    static cocos2d::Sprite *createVentanaAmigosSolicitudesSprite();
    static cocos2d::Sprite *createVentanaBorrarCharSprite();
    static cocos2d::Sprite *createVentanaBovedaCuentaCambiarContraseniaSprite();
    static cocos2d::Sprite *createVentanaBovedaCuentaPassSprite();
    static cocos2d::Sprite *createVentanaCambiarContraseniaSprite();
    static cocos2d::Sprite *createVentanaCantidadSprite();
    static cocos2d::Sprite *createVentanaCargandoSprite();
    static cocos2d::Sprite *createVentanaClanAdminSprite();
    static cocos2d::Sprite *createVentanaClanInfoSprite();
    static cocos2d::Sprite *createVentanaClanMemberInfoSprite();
    static cocos2d::Sprite *createVentanaClanOfertaAlianzaSprite();
    static cocos2d::Sprite *createVentanaClanOfertaPazSprite();
    static cocos2d::Sprite *createVentanaClanSolicitudSprite();
    static cocos2d::Sprite *createVentanaClanVerSolicitudSprite();
    static cocos2d::Sprite *createVentanaComercioSprite();
    static cocos2d::Sprite *createVentanaConectarSprite();
    static cocos2d::Sprite *createVentanaConfigurarConsolaSprite();
    static cocos2d::Sprite *createVentanaConfigurarTeclasSprite();
    static cocos2d::Sprite *createVentanaCrafteoSprite();
    static cocos2d::Sprite *createVentanaCrearCuentaSprite();
    static cocos2d::Sprite *createVentanaCrearPersonajeSprite();
    static cocos2d::Sprite *createVentanaCuentaSprite();
    static cocos2d::Sprite *createVentanaDialogosSprite();
    static cocos2d::Sprite *createVentanaDuelo1v1Sprite();
    static cocos2d::Sprite *createVentanaDuelo2v2Sprite();
    static cocos2d::Sprite *createVentanaDuelo3v3Sprite();
    static cocos2d::Sprite *createVentanaDuelo4v4Sprite();
    static cocos2d::Sprite *createVentanaDuelosSprite();
    static cocos2d::Sprite *createVentanaEditarCodexSprite();
    static cocos2d::Sprite *createVentanaEditarWebsiteSprite();
    static cocos2d::Sprite *createVentanaEsperandoDueloSprite();
    static cocos2d::Sprite *createVentanaEstadisticaold_sSprite();
    static cocos2d::Sprite *createVentanaEstadisticasSprite();
    static cocos2d::Sprite *createVentanaListaClanesSprite();
    static cocos2d::Sprite *createVentanaMapaSprite();
    static cocos2d::Sprite *createVentanaMascotasSprite();
    static cocos2d::Sprite *createVentanaMensajesPersonalizadosSprite();
    static cocos2d::Sprite *createVentanaNoticiasClanSprite();
    static cocos2d::Sprite *createVentanaOpcionesSprite();
    static cocos2d::Sprite *createVentanaPrincipalSprite();
    static cocos2d::Sprite *createVentanaResolucionSprite();
    static cocos2d::Sprite *createVentanaSkillsSprite();
    static cocos2d::Sprite *createVentanaTutorialSprite();

	static cocos2d::Vector<cocos2d::SpriteFrame*> getPRESENTACIONAnimationFrames();
	static cocos2d::Animate* createPRESENTACIONAnimateAction(float delay, unsigned int loops);

}; // class

}; // namespace

#endif // __INTERFACE_H__
