#ifndef __EVENT_LIST_H__
#define __EVENT_LIST_H__

#include "SlikeNet/MessageIdentifiers.h"

enum Signals
{
	FIRST = ID_USER_PACKET_ENUM + 1,	//USED for iteration DO NOT REMOVE

	//Server
	NW_SEND_CLIENT,
	NW_SEND_BROADCAST,
	NW_SERVER_SYNC_PLAYERS,

	//Both
	HEALTH_USE_POTION,
	MANA_USE_POTION,

	NW_REQUEST_ENTT,
	NW_MY_ENTT,
	NW_ENTT_JOINED,
	NW_ENTT_QUIT,
	NW_SYNC_PLAYERS,

	MOVE_RENOCK,

	COMBAT_PUNCH,
	COMBAT_SPELLS_THROW,
	COMBAT_SPELLS_TARGET,
	COMBAT_SPELLS_AIR,
	COMBAT_PUNCH_TARGET,
	COMBAT_PUNCH_AIR,
	COMBAT_DEAD,
	COMBAT_RESURRECT,

	MEDITATE,
	MEDITATE_START,
	MEDITATE_END,

	HEALTH_UPDATE,
	MANA_UPDATE,

	ANIMATE_WALK,
	ANIMATE_SET_BODY_ALL,
	ANIMATE_SET_BODY,
	ANIMATE_SET_HEAD,
	ANIMATE_SET_HELMET,
	ANIMATE_SET_SHIELD,
	ANIMATE_SET_WEAPON,
	ANIMATE_SPELL,
	ANIMATE_WEAPON,
	ANIMATE_SHIELD,

	//Client
	NW_SEND_SERVER,
	NW_CONNECT,
	NW_DISCONNECT,

	UI_LBL_NETWORK,
	UI_SPELL_TRHOUW,
	UI_TOGGLE_FULLSCREEN,
	UI_TOGGLE_DEBUG,
	UI_CAMERA_ZOOM_IN,
	UI_CAMERA_ZOOM_OUT,
	UI_TOGGLE_VSYNC,
	UI_UPDATE_DEBUG,

	APP_DID_ENTER_BG,
	APP_WILL_ENTER_FG,

	AUDIO_FX_CREATE,
	AUDIO_FX_REMOVE,
	AUDIO_TOGGLE_FX,
	AUDIO_TOGGLE_MUSIC,
	AUDIO_SET_MUSIC_TRACK,

	GRAPHICS_LOAD_BODY,
	GRAPHICS_LOAD_HEAD,
	GRAPHICS_LOAD_HELMET,
	GRAPHICS_LOAD_SHIELD,
	GRAPHICS_LOAD_WEAPON,
	GRAPHICS_RELOAD_INSTANCE,

	MOVE_NORTH,
	MOVE_EAST,
	MOVE_SOUTH,
	MOVE_WEST,
	MOVE_STOP,
	SWITCH_FACING,

	CAMERA_ZOOM_IN,
	CAMERA_ZOOM_OUT,

	MAP_ADD_PLAYER,
	MAP_REM_PLAYER,
	MAP_CAN_MOVE,
	MAP_TOGGLE_DEBUG,

	INVENTORY_SYNC,
	INVENTORY_ITEM_USE,
	INVENTORY_ITEM_UPDATE,

	PARTICLES_ANIM_SPAWN,
	PARTICLES_ANIM_UNSPAWN,

	LAST	//USED for iteration DO NOT REMOVE
};

#endif // __EVENT_LIST_H__